CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    username varchar (255) NOT NULL, 
    title VARCHAR(55) NOT NULL,
    text VARCHAR(1000) NOT NULL,
    img_url VARCHAR(1000),
    public BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);